# Generated by Django 3.0.5 on 2020-05-08 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='tag_name',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='assigned',
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_issue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='tag',
            field=models.ManyToManyField(related_name='tasIssues', to='tracker.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='IssueAssignment',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='issue',
        ),
    ]
