# Generated by Django 3.0.5 on 2020-05-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200511_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tagIssues', to='tracker.Tag'),
        ),
    ]
