# Generated by Django 3.0.5 on 2020-05-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20200511_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tagIssues', to='tracker.Tag'),
        ),
    ]
