# Generated by Django 3.0.5 on 2020-05-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20200518_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserId',
            field=models.BigIntegerField(default=0),
        ),
    ]
