# Generated by Django 3.0.5 on 2020-05-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20200518_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.BigIntegerField(unique=True),
        ),
    ]
