# Generated by Django 3.0.5 on 2020-05-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20200518_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
