# Generated by Django 3.0.5 on 2020-05-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrollmentNumber',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
