# Generated by Django 3.0.5 on 2020-05-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20200518_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
