# Generated by Django 3.0.5 on 2020-05-31 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_media'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='ProjectMedia',
        ),
        migrations.CreateModel(
            name='IssueMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(upload_to='upload_images')),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_media', to='tracker.Issue')),
            ],
        ),
    ]
